name: Deploy portfolio

on:
  push:
    branches: ['cicd_cfg']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build --prod

      - name: Archive build artifact
        uses: actions/upload-artifact@main
        with:
          name: portfolio
          path: ./dist/portfolio
  upload:
    name: Upload to server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: ${{ env.artifactPath }}
          target: ${{ secrets.DEPLOY_PATH }}
          tar_tmp_path: /home/${{ secrets.DEPLOY_USERNAME }}
          rm: true
