name: dev.jmuzina.io

on:
  push:
    branches: [ 'dev' ]

jobs:
  deploy-portfolio:
    name: Deploy Portfolio to Dev environment
    uses: 'jmuzina/portfolio/.github/workflows/deploy-portfolio.yml@dev'
    with:
      environment: dev
    secrets:
      AWS_S3_BUCKET_NAME: ${{ secrets.DEV_AWS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.DEV_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
