name: dev.jmuzina.io

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

on:
  push:
    branches: ['dev']

jobs:
  deploy:

    name: Build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Angular dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build:dev

      - name: Generate sourcemaps
        run: npm run sentry:sourcemaps

      - name: Archive build artifact
        uses: actions/upload-artifact@main
        with:
          name: portfolio
          path: ./dist/portfolio

      - name: Deploy build files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: ./dist/portfolio
          target: ${{ secrets.DEPLOY_PATH }}/development
          tar_tmp_path: /home/${{ secrets.DEPLOY_USERNAME }}/tmp/development
          rm: true
          timeout: 60s
