name: dev.jmuzina.io

on:
  push:
    branches: [ 'dev' ]
  workflow_dispatch:


jobs:
  build-portfolio:
    name: Build Development portfolio
    uses: 'jmuzina/portfolio/.github/workflows/ci.yml@dev'
    with:
      environment: dev
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  deploy-portfolio:
    needs: build-portfolio
    name: Deploy Portfolio to Dev environment
    uses: 'jmuzina/deploy_s3_with_cloudfront_invalidation/.github/workflows/deploy_s3_cloudfront.yml@1.0.0'
    with:
      environment: dev
    secrets:
      AWS_S3_BUCKET_NAME: ${{ secrets.DEV_AWS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.DEV_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
