name: PR Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Angular dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build Angular
        run: npm run build:dev && rm -rf dist && npm run build:prod
