name: jmuzina.io

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-portfolio:
    name: Build Production portfolio
    uses: 'jmuzina/portfolio/.github/workflows/ci.yml@main'
    with:
      environment: prod
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  deploy-portfolio:
    needs: build-portfolio
    name: Deploy Portfolio to Prod environment
    uses: 'jmuzina/deploy_s3_with_cloudfront_invalidation/.github/workflows/deploy_s3_cloudfront.yml@1.0.0'
    with:
      environment: prod
    secrets:
      AWS_S3_BUCKET_NAME: ${{ secrets.PROD_AWS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.PROD_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
