name: Deploy portfolio to Production

on:
  push:
    branches: ['main']

jobs:
  deploy:

    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Angular dependencies
        run: npm ci

      - name: Build Angular
        run: npx ng build --configuration production

      #- name: Archive build artifact
      #  uses: actions/upload-artifact@main
      #  with:
      #    name: portfolio
      #    path: ./dist/portfolio

      - name: Deploy build files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: ./dist/portfolio
          target: ${{ secrets.DEPLOY_PATH }}/production
          tar_tmp_path: /home/${{ secrets.DEPLOY_USERNAME }}/tmp/production
          rm: true
          timeout: 60s
