name: jmuzina.io

on:
  push:
    branches: [ 'main' ]

jobs:
  build-portfolio:
    name: Build Production portfolio
    uses: 'jmuzina/portfolio/.github/workflows/ci.yml@main'
    with:
      environment: prod
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  deploy-portfolio:
    needs: build-portfolio
    name: Deploy Portfolio to Prod environment
    uses: 'jmuzina/portfolio/.github/workflows/cd.yml@main'
    with:
      environment: prod
    secrets:
      AWS_S3_BUCKET_NAME: ${{ secrets.PROD_AWS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.PROD_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
